### ISSUE TITLE
Make the library usable without a dynamic classloader

### ISSUE THREAD

**Issue by crclark** [clojure-goes-fast/clj-memory-meter#2]
Clojure version: 1.9.0
Leiningen version: 2.8.1
`java -version`: 1.8.0_181

https://gist.github.com/crclark/9e111183c5c55b557c93ecb350da5331

With the above minimal project, if I run `-main` from the repl, it works fine, but if I run the project with `lein run`, I get an [exception](https://gist.github.com/crclark/9bcf32948f1519e4572656ef09d7bfd2).

`Exception in thread "main" java.lang.ClassCastException: sun.misc.Launcher$AppClassLoader cannot be cast to clojure.lang.DynamicClassLoader, compiling:(clj_memory_meter/core.clj:18:1)`

**Comment by alexander-yakushev** [comment]
Hi, thanks for reporting this!

I figured out that when you do `lein run` (or whatever else non-REPL task that loads code, like `compile`), Leiningen doesn't establish a proper dynamic classloader that can add dependencies on the fly. `clj-memory-meter` currently requires such dynamic classloader to hotload Java's `tools.jar` dependency.

Now, the question is, do you really want to embed `clj-memory-meter` into the final application? If so, I would add a workaround on my side for cases like this, but then you would have to add `tools.jar` to the classpath manually whenever you launch the application. Is this something you need and are willing to do?

**Comment by crclark** [comment]
For what I'm working on, just repl support should be fine. For me, `lein run`/`lein compile` support isn't a high priority. Thanks!

**Comment by alexander-yakushev** [comment]
Cool! I'll keep this around to hopefully fix someday.

**Comment by TimoFreiberg** [comment]
I get the same exception in a CIDER session: `sun.misc.Launcher$AppClassLoader cannot be cast to clojure.lang.DynamicClassLoader`

I had to wrap the body of the `tools-jar-classloader` def into a `delay` to actually see the exception - before I just got a `namespace 'clj-memory-meter.core' not found`

Using java 8

**Comment by alexander-yakushev** [comment]
Could you please tell more about your setup? Are you running the project with Leiningen, or perhaps tools.deps?

**Comment by TimoFreiberg** [comment]
Yeah, the project I'm trying to use the memory meter in is using leiningen.

**Comment by alexander-yakushev** [comment]
Alright, so I assume you've added `clj-memory-meter.core` to the `:require` section, and the error happens when you restart CIDER? But if you don't have it in the initial requires and only execute `(require 'clj-memory-meter.core)` after CIDER has started, it works, am I correct on this?

**Comment by TimoFreiberg** [comment]
Oh wow. True, it works exactly as you said. I played around with it quite a bit, but never removed the require from the `ns`...

Is it important for the `tools-jar-classloader` to be evaluated immediately?
Maybe the `ClassCastException` could be wrapped into something that describes this problem and even suggests your solution

**Comment by alexander-yakushev** [comment]
Yes, I considered deferring any classloader-related actions until `measure` is first invoked, but then I thought there is value in failing in load time (when you require the namespace) rather than in first use time. Now that I think of it, it's not really worth the drawbacks.

**Comment by TimoFreiberg** [comment]
The way things were before, I didn't even see the real exception, I only got the `namespace 'clj-memory-meter.core' not found` error.
I'm not sure if that's caused by tooling differences though

**Comment by alexander-yakushev** [comment]
Yes, totally. I'm currently merging on your PR with some changes. Thank you!

**Comment by TimoFreiberg** [comment]
Glad I could help :)

**Comment by alexander-yakushev** [comment]
@crclark In case you ever need that, version `0.1.2` now can be usable outside of REPL :).
