### ISSUE TITLE
Wrong unit used in human readable

### ISSUE THREAD

**Issue by BrunoBonacci** [clojure-goes-fast/clj-memory-meter#4]
Very nice library!!.

Browsing the code I spotted a little issue in `convert-to-human-readable` at:
https://github.com/clojure-goes-fast/clj-memory-meter/blob/b502fda056ec4f069d32de8600a701535866a28e/src/clj_memory_meter/core.clj#L102

Historically 1KB was 1024 bytes, however since these measures have been incorporated in the International System of Units (SI) they have been uniformed with the other measures where **1 KB = 1000 bytes** and **1 MB is 1000000**. The power of 2 unit of 1024 it is now referred as **KiB**, **MiB**, **GiB** etc

Please see the following article.
https://en.wikipedia.org/wiki/Megabyte

So it is adviseable that you either update the unit to `1000` or the labels to `MiB` instead of `MB`.

**Comment by alexander-yakushev** [comment]
Good point! Thanks, Bruno. I've pushed a fix.
