### ISSUE TITLE
Doesn't work with JDK 12

### ISSUE THREAD

**Issue by thiru** [clojure-goes-fast/clj-memory-meter#5]
OS: Arch Linux
openjdk version "12.0.1" 2019-04-16
OpenJDK Runtime Environment (build 12.0.1+12)
OpenJDK 64-Bit Server VM (build 12.0.1+12, mixed mode)

I get the following error when evaluating `(mm/measure [])`:

```
java.lang.UnsatisfiedLinkError: no attach in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
java.lang.reflect.InvocationTargetException:
```

It does work with JDK 10.

**Comment by alexander-yakushev** [comment]
Hi! Do you use `-Djdk.attach.allowAttachSelf` flag?

**Comment by thiru** [comment]
Yup I did.  Without that it wouldn't work for me using JDK 10.

**Comment by alexander-yakushev** [comment]
Interesting. It works for me on JDK12 for almost that exact version. But I use the AdoptOpenJDK build on MacOS.
```
openjdk version "12.0.1" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 12.0.1+12)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 12.0.1+12, mixed mode, sharing)
```
Could you please paste the whole stacktrace (from `(pst)` or `*e`)?

**Comment by alexander-yakushev** [comment]
I googled the error, people had similar issues before when they were missing `tools.jar` in their JDK, or something was not on PATH, etc. Try googling around for clues, maybe one of the solutions will work for you.

**Comment by thiru** [comment]
Yeah you're right this isn't an issue with your library but with my install of Java on my work PC.  With JDK 12 on home PC (also Arch Linux with JDK 12) it works fine.  It may have to do with having multiple installs of Java on Arch.

Thanks for you help and your libraries!

**Comment by alexander-yakushev** [comment]
Cool, thanks for the update!
