### ISSUE TITLE
"Illegal reflective access" warning

### ISSUE THREAD

**Issue by pmonks** [clojure-goes-fast/clj-memory-meter#7]
JVM: OpenJDK 11.0.2+9 64 bit macOS
Clojure: 1.10.1
Clojure CLI: 1.10.1.590

## Steps to reproduce:
1. With the above stack, start a repl: `clj -J-Djdk.attach.allowAttachSelf -Sdeps '{:deps {com.clojure-goes-fast/clj-memory-meter {:mvn/version "0.1.2"}}}' -r`
2. Require the ns: `(require '[clj-memory-meter.core :as mm])`
3. Measure an object: `(mm/measure "Hello, world!")`

## Expected result:
```
$ clj -J-Djdk.attach.allowAttachSelf -Sdeps '{:deps {com.clojure-goes-fast/clj-memory-meter {:mvn/version "0.1.2"}}}' -r
Clojure 1.10.1
user=> (require '[clj-memory-meter.core :as mm])
nil
user=> (mm/measure "Hello, world!")
"56 B"
```

## Actual result:
```
$ clj -J-Djdk.attach.allowAttachSelf -Sdeps '{:deps {com.clojure-goes-fast/clj-memory-meter {:mvn/version "0.1.2"}}}' -r
Clojure 1.10.1
user=> (require '[clj-memory-meter.core :as mm])
nil
user=> (mm/measure "Hello, world!")
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by clojure.lang.InjectedInvoker/0x0000000800232040 (file:/Users/pmonks/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar) to method sun.tools.attach.VirtualMachineImpl.detach()
WARNING: Please consider reporting this to the maintainers of clojure.lang.InjectedInvoker/0x0000000800232040
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
"56 B"
```

**Comment by alexander-yakushev** [comment]
Hi! I've fixed this particular illegal access warning in `0.1.3-SNAPSHOT`, you can try it out.

The problem is, however, Jamm (the underlying library that clj-memory-meter uses) uses reflection on its own and produces such warnings as well. This, unfortunately, is out of my control.

**Comment by pmonks** [comment]
Looks good - closing.  See also https://github.com/jbellis/jamm/issues/35
